### ISSUE TITLE
Must be called from the context of Tokio runtime

### ISSUE THREAD

**Issue by ricardoalmeida** [async-graphql/examples#30]
Playing around examples/federation/gateway, I'm facing this issue when trying to start services federation-reviews, federation-accounts and federation-products

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /Users/ricardoalmeida/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/io/driver/mod.rs:204:14
```

**Comment by sunli829** [comment]
This is due to Warp still using Tokio 0.2, when we've upgraded to Tokio 0.3. It should be fixed now, I just had to use tokio-compat-02.
