### ISSUE TITLE
Error handling on Mutation

### ISSUE THREAD

**Issue by fgadaleta** [async-graphql/examples#47]
Running this example about error handling on mutation

`actix-web/error-extensions/src/main.rs`

I get 

```
error: cannot find derive macro `Error` in this scope
   | #[derive(Debug, Error)]
   |                 ^^^^^
```

How am I supposed to use `Error` with 
`actix-web = { version = "4.0.0-beta.13", default-features = false }` ?

**Comment by sunli829** [comment]
This macro is from the `thiserror` crate.
