### ISSUE TITLE
Actix token-from-header subscription example not work

### ISSUE THREAD

**Issue by huahouye** [async-graphql/examples#53]
run `cargo run` under [actix-web/token-from-header](https://github.com/async-graphql/examples/tree/master/actix-web/token-from-header) folder,open http://localhost:8080 with http header

```json
{
  "Token": "123456"
}
``` 
when try to subscribe to graphql get an error like this:

```json
{
  "error": "Could not connect to websocket endpoint ws://localhost:8000/ws. Please check if the endpoint url is correct."
}
```

I am new to async-graphql, donnot know how to make this example work.

![](https://s3.bmp.ovh/imgs/2022/06/27/7704dd17632fd141.png)

**Comment by hffmnn** [comment]
Did you make it work? Can you describe what you did?
