### ISSUE TITLE
Access arguments in child resolvers

### ISSUE THREAD

**Issue by mnnxp** [async-graphql/examples#90]
Hi there!

Looking for how to make getting arguments from child objects of a request, server side, using `async-graphql`.

For example, in this query, you can specify the material type as a child argument in addition to the main argument.
```bash
query($type: String!, $materialType: String) {
   Car(type: $type){
      id
      name
      carType
      material(materialType: $materialType) { # Type resolver with argument
        name
        materialType
      }
      ...
   }
}
```

Maybe there is an example or someone can suggest. :)

More detailed description of the same issue:
https://stackoverflow.com/questions/48382897/graphql-access-arguments-in-child-resolvers

**Comment by sansx** [comment]
One of my friend encounter similar issue before.

To retrieve arguments from child objects in a GraphQL query using `async-graphql`, you can utilize the resolver functions to access these arguments. Here’s how you can achieve this step by step, along with an example based on your query structure.

### Step-by-Step Guide

1. **Define Your Schema**: Make sure your schema includes the relevant types and fields, including the nested fields that accept arguments.

2. **Create Resolvers**: Implement resolvers for both the parent object (e.g., `Car`) and the child object (e.g., `material`), where the child resolver will accept arguments.

3. **Accessing Arguments**: Inside the child resolver, you can access the arguments using the `&Context` provided by `async-graphql`.

### Example Implementation

Here’s a simplified example based on your GraphQL query. Assume we have a `Car` type with a nested `material` field.

#### Step 1: Define Your GraphQL Types

```rust
use async_graphql::{Context, Object};

#[derive(Default)]
pub struct Query;

#[Object]
impl Query {
    async fn car(&self, ctx: &Context<'_>, type_: String) -> Car {
        // Logic to retrieve a Car by type
    }
}

#[derive(Default)]
pub struct Car {
    id: i32,
    name: String,
    car_type: String,
}

#[Object]
impl Car {
    async fn id(&self) -> i32 {
        self.id
    }

    async fn name(&self) -> &str {
        &self.name
    }

    async fn car_type(&self) -> &str {
        &self.car_type
    }

    async fn material(&self, ctx: &Context<'_>, material_type: Option<String>) -> Material {
        // Logic to retrieve material based on the optional material_type argument
        // Access the argument like this:
        // let material_type = material_type.unwrap_or_else(|| "default_material_type".to_string());
    }
}

#[derive(Default)]
pub struct Material {
    name: String,
    material_type: String,
}

#[Object]
impl Material {
    async fn name(&self) -> &str {
        &self.name
    }

    async fn material_type(&self) -> &str {
        &self.material_type
    }
}
```

#### Step 2: Create a Schema

```rust
use async_graphql::{Schema};

let schema = Schema::build(Query::default(), EmptyMutation, EmptySubscription)
    .finish();
```

### Explanation

- **Car Resolver**: In the `Car` object, you define a `material` function that accepts an optional `material_type` argument.
- **Accessing Arguments**: Inside the `material` resolver, you can access the `material_type` argument passed in the query.
- **Default Value Handling**: The example shows how to provide a default value if `material_type` is not specified.

### Final GraphQL Query

With this setup, your query can look like the one you provided:

```graphql
query($type: String!, $materialType: String) {
   Car(type: $type) {
      id
      name
      carType
      material(materialType: $materialType) {
        name
        materialType
      }
   }
}
```

### You can also check

- **Async-GraphQL Documentation**: Check the [Async-GraphQL Documentation](https://async-graphql.github.io/async-graphql/en/) for more examples and advanced features.
- **GraphQL Best Practices**: Understanding how to structure your GraphQL API effectively can help with maintainability and performance.

**Comment by mnnxp** [comment]
Awesome answer! Thank you!

**Comment by rbozan** [comment]
> One of my friend encounter similar issue before.
> 
> To retrieve arguments from child objects in a GraphQL query using `async-graphql`, you can utilize the resolver functions to access these arguments. Here’s how you can achieve this step by step, along with an example based on your query structure.
> 
> ### Step-by-Step Guide
> 1. **Define Your Schema**: Make sure your schema includes the relevant types and fields, including the nested fields that accept arguments.
> 2. **Create Resolvers**: Implement resolvers for both the parent object (e.g., `Car`) and the child object (e.g., `material`), where the child resolver will accept arguments.
> 3. **Accessing Arguments**: Inside the child resolver, you can access the arguments using the `&Context` provided by `async-graphql`.
> 
> ### Example Implementation
> Here’s a simplified example based on your GraphQL query. Assume we have a `Car` type with a nested `material` field.
> 
> #### Step 1: Define Your GraphQL Types
> use async_graphql::{Context, Object};
> 
> #[derive(Default)]
> pub struct Query;
> 
> #[Object]
> impl Query {
>     async fn car(&self, ctx: &Context<'_>, type_: String) -> Car {
>         // Logic to retrieve a Car by type
>     }
> }
> 
> #[derive(Default)]
> pub struct Car {
>     id: i32,
>     name: String,
>     car_type: String,
> }
> 
> #[Object]
> impl Car {
>     async fn id(&self) -> i32 {
>         self.id
>     }
> 
>     async fn name(&self) -> &str {
>         &self.name
>     }
> 
>     async fn car_type(&self) -> &str {
>         &self.car_type
>     }
> 
>     async fn material(&self, ctx: &Context<'_>, material_type: Option<String>) -> Material {
>         // Logic to retrieve material based on the optional material_type argument
>         // Access the argument like this:
>         // let material_type = material_type.unwrap_or_else(|| "default_material_type".to_string());
>     }
> }
> 
> #[derive(Default)]
> pub struct Material {
>     name: String,
>     material_type: String,
> }
> 
> #[Object]
> impl Material {
>     async fn name(&self) -> &str {
>         &self.name
>     }
> 
>     async fn material_type(&self) -> &str {
>         &self.material_type
>     }
> }
> #### Step 2: Create a Schema
> use async_graphql::{Schema};
> 
> let schema = Schema::build(Query::default(), EmptyMutation, EmptySubscription)
>     .finish();
> ### Explanation
> * **Car Resolver**: In the `Car` object, you define a `material` function that accepts an optional `material_type` argument.
> * **Accessing Arguments**: Inside the `material` resolver, you can access the `material_type` argument passed in the query.
> * **Default Value Handling**: The example shows how to provide a default value if `material_type` is not specified.
> 
> ### Final GraphQL Query
> With this setup, your query can look like the one you provided:
> 
> query($type: String!, $materialType: String) {
>    Car(type: $type) {
>       id
>       name
>       carType
>       material(materialType: $materialType) {
>         name
>         materialType
>       }
>    }
> }
> ### You can also check
> * **Async-GraphQL Documentation**: Check the [Async-GraphQL Documentation](https://async-graphql.github.io/async-graphql/en/) for more examples and advanced features.
> * **GraphQL Best Practices**: Understanding how to structure your GraphQL API effectively can help with maintainability and performance.

????

Is this an AI response or what? So how do you do this?
